[package]
name = "shc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.13"
dialoguer = "0.11.0"
dirs = "5.0.1"
serde =  {version = "1.0.195", features = ["derive"]} 
toml = "0.8.8"
